theme = "lynx"
title = "Sionnach's Website"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Sionnach"
  headline = "Irish anarchist who will hopefully write something someday<br>I encourage you to reduce your time on social media and use more ethical and healthy alternatives or get involved and take prefigurative action in real life!<br>I like to print and freely distritube zines. If you would like me to give out zines at an event, get in contact!"
  image = "favicon.png"
  links = [
    { writing = { href = "writings/", text = "My Writings" } },
    { reading = { href = "readings/", text = "Recommended Reading" } },
    { mastodon = "https://kolektiva.social/@Sionnach" },
    { kofi = { href = "https://ko-fi.com/sionnachxyz", text = "Donate (Ko-Fi)" } },
    { ainriail = { href = "https://ainriail.org", text = "Ainriail - Dublin Event Noticeboard" } },
    { youtube = "https://youtube.com/@sionnachxyz" },
    { email = { href = "mailto:contact-sionnach.truffle781@slmails.com", text = "Contact (Email)" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
